DROP TABLE IF EXISTS UESRS;

CREATE TABLE IF NOT EXISTS USERS (
    ID INT AUTO_INCREMENT,
    UID VARCHAR(255),
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(255),
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS DATASET (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(255),
    PATH VARCHAR(255),
    SIZE INT,
    CREATED_BY INT,
    UPDATED_BY INT,
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    PRIMARY KEY (ID),
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID),
    FOREIGN KEY (UPDATED_BY) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS IMAGE (
    ID INT AUTO_INCREMENT,
    DATASET_ID INT,
    NAME VARCHAR(255),
    URL VARCHAR(255),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    PRIMARY KEY (ID),
    FOREIGN KEY (DATASET_ID) REFERENCES DATASET(ID) ON UPDATE CASCADE
);