DROP TABLE IF EXISTS UESRS;

CREATE TABLE IF NOT EXISTS USERS (
    ID INT AUTO_INCREMENT,
    UID VARCHAR(255),
    NAME VARCHAR(255),
    CREATED DATETIME,
    UPDATED DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS DATASET (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(255),
    PATH VARCHAR(255),
    SIZE INT,
    CREATED DATETIME,
    UPDATED DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS IMAGE (
    ID INT AUTO_INCREMENT,
    DATASET_ID INT,
    NAME VARCHAR(255),
    URL VARCHAR(255),
    CREATED DATETIME,
    UPDATED DATETIME,
    PRIMARY KEY (ID),
    FOREIGN KEY (DATASET_ID) REFERENCES DATASET(ID) ON UPDATE CASCADE
);