version: "3"
services:
  app:
    image: rest-app:230521
    container_name: rest-app
    networks:
      - server-network
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./resources:/opt/app/resources
    # healthcheck:
    #   test: ["executable", "arg"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s

networks:
  server-network:
    name: server-network
