name: Application Deployment

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@4
      with:
        images: rmk1075/spring-boot-rest
        tags: |
          type=ref, event=branch
          type=ref, event=tag

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          # platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
