name: Application Integration

# on:
#   pull_request:
#     branches: ["*"]
on: [push]

jobs:
  test_java_application:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: adopt
    - name: Gradle tests
      run: |
        ./gradlew test
